## CHI-SQUARE TEST

#### Association between Device Type and Customer Satisfaction

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [12]:
##Creating a dataframe by the given data

df = pd.DataFrame({
    "Satisfaction" : ["Very Satisfied","Satisfied","Neutral","Unsatisfied","Very Unsatisfied"],
    "Smart Thermostat": [50,80,60,30,20],
    "Smart Light": [70,100,90,50,50],
    "Total" : [120,180,150,80,70]
                   
})

In [13]:
df

Satisfaction  Smart Thermostat  Smart Light  Total
0    Very Satisfied                50           70    120
1         Satisfied                80          100    180
2           Neutral                60           90    150
3       Unsatisfied                30           50     80
4  Very Unsatisfied                20           50     70

In [14]:
df.info

<bound method DataFrame.info of        Satisfaction  Smart Thermostat  Smart Light  Total
0    Very Satisfied                50           70    120
1         Satisfied                80          100    180
2           Neutral                60           90    150
3       Unsatisfied                30           50     80
4  Very Unsatisfied                20           50     70>

In [15]:
df.shape

(5, 4)

In [16]:
df.describe()

Smart Thermostat  Smart Light       Total
count          5.000000     5.000000    5.000000
mean          48.000000    72.000000  120.000000
std           23.874673    22.803509   46.368092
min           20.000000    50.000000   70.000000
25%           30.000000    50.000000   80.000000
50%           50.000000    70.000000  120.000000
75%           60.000000    90.000000  150.000000
max           80.000000   100.000000  180.000000

##### To use the Chi-Square test for independence to determine if there's a significant association between the type of smart home device purchased (Smart Thermostats vs. Smart Lights) and the customer satisfaction level.

##### 1. State the Hypotheses:

Ho:There is no significant association between the type of smart home device purchased (Smart Thermostats vs. Smart Lights) and the customer satisfaction level.

Ha:There is a significant association between the type of smart home device purchased (Smart Thermostats vs. Smart Lights) and the customer satisfaction level.

##### 2.Compute the Chi-Square Statistic:

In [25]:
data = df[['Smart Thermostat','Smart Light']].values
print(data)


[[ 50  70]
 [ 80 100]
 [ 60  90]
 [ 30  50]
 [ 20  50]]


In [26]:
import scipy.stats as stats
from scipy.stats import chi2_contingency

chi2_stat,p_val,dof,expected = stats.chi2_contingency(data)
chi2_stat,p_val,dof,expected

(5.638227513227513,
 0.22784371130697179,
 4,
 array([[ 48.,  72.],
        [ 72., 108.],
        [ 60.,  90.],
        [ 32.,  48.],
        [ 28.,  42.]]))

Formula to calculate Expected value: E = (Total_rows * Total_columns)/Grand_total

Formula to calculate Chi-Squared Statistics : chi_square = summation[(Observed_value - Expected_value)**2/Expected_value]

In [27]:
chi_square = sum([(o-e)**2/e for o,e in zip(data, expected)])
chi_square

array([3.38293651, 2.25529101])

In [28]:
chi_square_statistics = chi_square[0]+chi_square[1]
chi_square_statistics

### We can see manual way and using the function gave the same chi_stats value (that is 5.638227513227513)


5.638227513227513

##### 3. Determine the Critical Value:
Using the significance level (alpha) of 0.05 and the degrees of freedom (which is the number of categories minus 1)


In [30]:
from scipy.stats import chi2

alpha=0.05

critical_value = chi2.ppf(q=1-alpha, df=dof)   
print("The Critical Value is : ",critical_value)

The Critical Value is :  9.487729036781154


##### 4. Make a Decision:

As Critical_value > chi_square_statictics 

Hence we will failed to reject Ho(Null Hypothesis)

## HYPOTHESIS TESTING

Objective:
To investigate the restaurant owners' claim about the increase in weekly operating costs using hypothesis testing.


Data Provided:
•	The theoretical weekly operating cost model: W = $1,000 + $5X
•	Sample of 25 restaurants with a mean weekly cost of Rs. 3,050
•	Number of units produced in a week (X) follows a normal distribution with a mean (μ) of 600 units and a standard deviation (σ) of 25 units


#### 1. State the Hypotheses statement:

Ho :W = $1,000 + $5X that means there is no increase in the weekly operating costs.
Ha :W > $1,000 + $5X that means there is an increase in the weekly operating costs.

In [32]:
# data given:
µ = 1000+5*600    #(here 600 is units produced in a week)
sigma_pop = 5*25   # 25 is the units
n=25               # sample size
x_bar = 3050       # sample mean 
alpha = 0.05       # significance level

#### 2.Calculate the Test Statistic:

In [33]:
## T_statistics = (sample_mean - population mean)/(sigma_population/sqrt(sample_size))

t_statistics = (x_bar - µ)/(sigma_pop/np.sqrt(n))
t_statistics 


-38.0

In [34]:
## Alpha value is given as 0.05
z_critical = 1.645 

From the above calculations we can see that 
t_statistics < z_critical:

Hence we failed to reject Null Hypothesis.